# Generated by Django 4.2.2 on 2025-08-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_avatar_alter_user_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=100, verbose_name="Имя"),
        ),
    ]
