# Generated by Django 5.2.3 on 2025-07-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentry",
            name="number_of_views",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
