# Generated by Django 5.2.3 on 2025-07-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blogentry_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentry",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/", verbose_name="Превью"
            ),
        ),
    ]
