# Generated by Django 5.2.3 on 2025-07-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blogentry_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentry",
            name="publication_sign",
            field=models.BooleanField(default=False, verbose_name="Опубликовать?"),
        ),
    ]
