# Generated by Django 4.2.2 on 2025-08-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication_sign",
            field=models.BooleanField(default=False, verbose_name="Опубликовать?"),
        ),
    ]
